settings:
  title: 'Status Page'
  url: 'https://status-page.jjff.cloudns.org' # used for Slack messages
  logo: logo-192x192.png # image in ./public/ folder
  daysInHistogram: 1 # number of days you want to display in histogram
  collectResponseTimes: true # collects avg response times from CRON locations

  allmonitorsOperational: 'All Systems Operational'
  notAllmonitorsOperational: 'Not All Systems Operational'
  monitorLabelOperational: 'Operational'
  monitorLabelNotOperational: 'Not Operational'
  monitorLabelNoData: 'No data'
  dayInHistogramNoData: 'No data'
  dayInHistogramOperational: 'All good'
  dayInHistogramNotOperational: ' incident(s)' # xx incident(s) recorded

monitors:
  - id: workers-cloudflare-com # unique identifier
    name: workers.cloudflare.com
    description: 'You write code. They handle the rest.' # default=empty
    url: 'https://workers.cloudflare.com/' # URL to fetch
    method: GET # default=GET
    expectStatus: 200 # operational status, default=200
    followRedirect: false # should fetch follow redirects, default=false
    linkable: false # allows the title to be a link, default=true

  - id: www-cloudflare-com
    name: www.cloudflare.com
    description: 'Built for anything connected to the Internet.'
    url: 'https://www.cloudflare.com'
    method: GET
    expectStatus: 200
    linkable: true # allows the title to be a link, default=true

  - id: blog
    name: 博客
    description: 'Built for anything connected to the Internet.'
    url: 'https://bk.xjf520.cloudns.org'
    method: GET
    expectStatus: 200
    linkable: true # allows the title to be a link, default=true

  - id: jingtai
    name: 静态导航
    description: 'Built for anything connected to the Internet.'
    url: 'https://x.521.cloudns.org'
    method: GET
    expectStatus: 200
    linkable: true # allows the title to be a link, default=true

  - id: xiaokuma
    name: 小kuma
    description: 'Built for anything connected to the Internet.'
    url: 'https://xjfkkk-uptime-kuma.hf.space/dashboard'
    method: GET
    expectStatus: 200
    linkable: true # allows the title to be a link, default=true

  - id: kuma
    name: kuma
    description: 'Built for anything connected to the Internet.'
    url: 'https://kuma.1003.cloudns.org/status/web'
    method: GET
    expectStatus: 200
    linkable: true # allows the title to be a link, default=true

  - id: liangzi
    name: 量子影视
    description: 'Built for anything connected to the Internet.'
    url: 'https://4399.rr.nu'
    method: POST
    expectStatus: 200
    linkable: true # allows the title to be a link, default=true
