settings:
  title: 'Status Page'
  url: 'https://status-page.jjff.cloudns.org' # used for Slack messages
  logo: logo-192x192.png # image in ./public/ folder
  daysInHistogram: 60 # number of days you want to display in histogram
  collectResponseTimes: true # collects avg response times from CRON locations

  allmonitorsOperational: 'All Systems Operational'
  notAllmonitorsOperational: 'Not All Systems Operational'
  monitorLabelOperational: 'Operational'
  monitorLabelNotOperational: 'Not Operational'
  monitorLabelNoData: 'No data'
  dayInHistogramNoData: 'No data'
  dayInHistogramOperational: 'All good'
  dayInHistogramNotOperational: ' incident(s)' # xx incident(s) recorded

monitors:
  - id: uptimerobot
    name: uptimerobot
    description: 'Built for anything connected to the Internet.'
    url: 'https://stats.uptimerobot.com/dXm3wy0mA0'
    method: GET
    expectStatus: 200
    linkable: true # allows the title to be a link, default=true

  - id: uptimeflare
    name: uptimeflare
    description: 'Built for anything connected to the Internet.'
    url: 'https://uptimeflare-c1z.pages.dev'
    method: GET
    expectStatus: 200
    linkable: true # allows the title to be a link, default=true

  - id: xiaokuma
    name: 小kuma
    description: 'Built for anything connected to the Internet.'
    url: 'https://xjfkkk-uptime-kuma.hf.space/dashboard'
    method: GET
    expectStatus: 200
    linkable: true # allows the title to be a link, default=true

  - id: kuma
    name: kuma
    description: 'Built for anything connected to the Internet.'
    url: 'https://kuma.1003.cloudns.org/status/web'
    method: GET
    expectStatus: 200
    linkable: true # allows the title to be a link, default=true
    
  - id: blog
    name: 博客
    description: 'Built for anything connected to the Internet.'
    url: 'https://bk.xjf520.cloudns.org'
    method: GET
    expectStatus: 200
    linkable: true # allows the title to be a link, default=true

  - id: jingtai
    name: 静态导航
    description: 'Built for anything connected to the Internet.'
    url: 'https://x.521.cloudns.org'
    method: GET
    expectStatus: 200
    linkable: true # allows the title to be a link, default=true

  - id: liangzi
    name: 量子影视
    description: 'Built for anything connected to the Internet.'
    url: 'https://4399.rr.nu'
    method: POST
    expectStatus: 200
    linkable: true # allows the title to be a link, default=true
